server:
    port: 8000

spring:
  datasource:
     url: jdbc:mysql://39.104.165.155:3306/BUPT_IOT?useUnicode=true&characterEncoding=utf8
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver