server:
    port: 8000

spring:
  datasource:
     url: jdbc:mysql://39.104.165.155:3306/BUPT_IOT
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver

filter:
  timefilter:
    forwardDays: 10
    threhold: 5
  locationfilter:
    threhold: 0.5

service:
  threhold: 3

deviceAccess:
  host: 127.0.0.1
  port: 8100