server:
    port: 8000

spring:
  datasource:
     url: jdbc:mysql://39.104.165.155:3306/BUPT_IOT?useUnicode=true&characterEncoding=utf8
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver

account:
  host: account
  port: 8400
  check_url: http://account:8400/api/v1/account/check_token
  login_url: http://account:8400/api/v1/account/login
  client_id: client_2
  client_secret: 123456
  internal_client_id: client_1
  internal_client_secret: 123456